language: java
jdk:
- oraclejdk8
before_deploy:
- "./gradlew generatePomFileForMavenPublication"
deploy:
- provider: s3
  upload-dir: output
  bucket: cromulence.travis.objecttranslator
  region: eu-west-2
  access_key_id: AKIAJOKA7XFXV6MDKCPA
  secret_access_key:
    secure: vmMptVtx2ebXYQQ1JfA0Ba5PhvVfKvhyjjoW8G7dSkakutqYBoVxEuMqAoyUYVmAgBbkOeEkwzVTtw3OmB7Q5eAL33/oW+WG60nAVUUgM3TiEn8lPMK8hi5A6S3RDYyqP3D+b/peGhPnAWU/H6Rxd+UE2cPf1nHoznuWB05tV78r9wKv2N3Eft14mwy6JnfMKeJOEvdorTm1RlX4ZasLBueFS+xSAd8ABnRDlX9Q9t9gSEWPAWyMiugg3x00tcoJE1CoDRHaYd3Z8cpzEeDHUXymzFbL9Us6bBCAOY4Kl2CwyiKixe+6RpQJIfNfASvtPTGssevHmt2BBcHy/4H98CkOmcSXHY5abejFyQCrZk4zXsJlieQPEZMM7Ps7J9eP1hFD0/r15pEA1jMjEwDUKRhoUU5DTocdjgHyHVbG/nf0+4376kn8SnnIS2akgvb7gywx1EQz7jGJUqRDyCu9UajFp44nSeld+CH8FBSKtJKX57o1Y/3xWNo01XgGIXUPjnaiKiroyKm3FLT7BBLjgOTQddWo1jyND+v0qcX1xjSep8QTgZa95TnLKuELU8zgQy8NnH6gkVrprhDxvJFVzolynD2HFFOI2yzMznSMp1Wyzxkh6yodWRht4noN/naOvHYMBrq9XYzuG+AII6gSfFZ8ldE4PwnAOHD87N7ccKU=
- provider: bintray
  file: bintray.json
  user: maven
  key:
    secure: MzQD1yLmR/A/bGh82g0ljTFTgnBZA0qLOFZxur9FN/RUERv23cHFqhXLj3ct/Kk652CBe0DpZJpUiuV208o+gtOrN2ZV+L4SwJGRljJCGcg/7LsYRfkmF8IiBz682Rlo+PTkVnJJ3a/5d2uTgORcleerIncg9csZK3UPNIxQeZVXJYDNaGpVIkHeoZ+uiZjGf/9ud9JGBs+W5pPSX3pD01k0OzRi/mMetTnGK6XWvPIvB4s5oIwpLrylRqZK1Sc+GQf/wmHTP4ZXPhBRbqsZ4pQLN2NScRnAeMLO6QmfgH9YHx+8tojyfLWSajXCuEVQWU9EFZo135I+Ys4OXUCGKAOqcZvYX28BNlOsq12jdQscQFOKvMIEmp/3ujbIBCpID5dOmbx58eUJ0RtO/fNpaltBqKxGAcBxTu6VHyeTAqHEcgHkExWV09UutK7djNLUJqnVablaZ88hrcu7BYINkncmWNOwZB+xXKC5ZGK7sKSVbFAMxV5sCvgQiE2vzSVIVYxn87gn7J1tt4YpVSGnvCeUx12nB1kadgP/WOu7XMgjs6DQbo41Ee9ucE8rITCFXjdEvcwUkuQieyWhme/ibA5SP/C9L6cdqi9L8fW85x1ZU12NrCHah21cWv/ifW3CsthB6Pjp/ZX70uW/EMwu54V74WMmAHoNU67HybZ/h88=
  dry-run: false
